spring:
  application:
    name: HR-App
  profiles:
    active: ${ACTIVE_PROFILES:'dev,h2'}
  jpa:
    open-in-view: false
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 100
      return-body-on-create: true
      return-body-on-update: true
  jackson:
    visibility:
      field: any

server:
  port: ${SERVER_PORT:8090}

logging:
  level:
    com:
      trescomas: trace

hrapp:
  jwt:
    secret: ${JWT_SECRET:'zdtlD3JK56m6wTTgsNFhqzjqP'}
    issuer: ${JWT_ISSUER:'hrapp.io'}
